version: '2'
services:
    x3-webdav:
        image: my_private_registry/user/x3-webdav:build
        build: ../../
        container_name : 'x3-webdav-build'
        hostname: webdav.x3rus.com
        environment:
            - TERM=xterm
            - TZ=America/Montreal
            - USERS_PASS=thomas=toto
#        volumes:
#            -  /tmp/webdavUpload:/usr/local/apache2/uploads    # uid=33(www-data)
#            -  /tmp/htpasswd-webdav:/usr/local/apache2/user.passwd
 
    x3-webdav-cli:
        image: my_private_registry/user/x3-webdav-int-validation:build
        build: webdav-cli/.
        container_name : 'x3-webdav-int-validation-b'
        hostname: webdav-cli.x3rus.com
        environment:
            - TERM=xterm
            - TZ=America/Montreal
        links:
            - x3-webdav:webdav
